name: automatically merge dependabot PR's
on:
  pull_request:
    branches: [ master ]

jobs:
  run-unit-test:
    name: run unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: 16

      - name: run unit tests
        run: echo "unit test passed"

  auto-merge-dependabot:
    name: 🤖 Auto merge dependabot PR
    timeout-minutes: 10
    needs: [ run-unit-test ]
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: 🤖 Merge PR from dependabot
        uses: fastify/github-action-merge-dependabot@v3.6.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: minor
          merge-method: rebase
